import Footer from "@/components/common/footer";
import Header from "@/components/common/header";
import HomePage from "@/components/layout/home-page/home-page";
import Head from "next/head";
import styled from "styled-components";

const StyledMain = styled.main`
  position: relative;
  z-index: 1;
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
        <Header />
        <HomePage />
        <Footer />
      </StyledMain>
    </>
  );
}
